load("@npm//@bazel/typescript:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "google_visualization",
    srcs = [
        "google_visualization.ts",
    ],
    deps = [
        "@npm//@types/google.visualization",
    ],
)
