load("@npm_bazel_typescript//:index.bzl", "ts_library")

package(default_visibility = ["//frontend:__subpackages__"])

ts_library(
    name = "utils",
    srcs = [
        "utils.ts",
    ],
    deps = [
        "@org_xprof//frontend/app/common/interfaces",
    ],
)


