# Description:
#  Tools for building the Profile Tensorboard plugin pip package.
package(default_visibility = ["//visibility:private"])

licenses(["notice"])  # Apache 2.0

package_group(
    name = "internal",
    packages = [
        "//...",
    ],
)

# rm -rf /tmp/profile-pip
# bazel run plugin:build_pip_package
sh_binary(
    name = "build_pip_package",
    srcs = ["build_pip_package.sh"],
    data = [
        "MANIFEST.in",
        "setup.py",
        "//:README.md",
        "//:requirements.in",
        "//:skills_files",
        "@org_xprof//frontend:bundle.js",
        "@org_xprof//frontend:css",
        "@org_xprof//frontend:runtime.js",
        "@org_xprof//frontend:zone.js",
        "@org_xprof//frontend/app/components/trace_viewer_v2:assets/Roboto-Regular.ttf",
        "@org_xprof//frontend/app/components/trace_viewer_v2:trace_viewer_v2_wasm",
        "@org_xprof//plugin/xprof:profile_data",
        "@org_xprof//plugin/xprof:profile_io",
        "@org_xprof//plugin/xprof:resources",
        "@org_xprof//plugin/xprof:server",
        "@org_xprof//plugin/xprof:version",
        "@org_xprof//plugin/xprof/api:continuous_profiling_snapshot",
        "@org_xprof//plugin/xprof/cli:xprof_cli_lib",
        "@org_xprof//plugin/xprof/convert:all_libs",
        "@org_xprof//plugin/xprof/integration_tests/tpu/tensorflow:tpu_tf2_keras_xla",
        "@org_xprof//plugin/xprof/protobuf:protos_all",
        "@org_xprof//plugin/trace_viewer:trace_viewer_index.html",
        "@org_xprof//plugin/trace_viewer:trace_viewer_index.js",
        "@org_xprof//xprof/pywrap:_pywrap_profiler_plugin",
    ],
    tags = [
        "local",
        "manual",
    ],
)
