load("@npm//@bazel/concatjs:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "dashboard",
    srcs = [
        "dashboard.ts",
    ],
    deps = [
        "@npm//@types/google.visualization",
        "@org_xprof//frontend/app/common/interfaces",
    ],
)
