/** URL when running locally */
export const LOCAL_URL = '/';

/** Plugin name */
export const PLUGIN_NAME = 'profile';

/** Pefix of API */
export const API_PREFIX = '/data/plugin/';

/** Runs API */
export const RUNS_API = API_PREFIX + PLUGIN_NAME + '/runs';

/** Tools per run API */
export const RUN_TOOLS_API = API_PREFIX + PLUGIN_NAME + '/run_tools';

/** Hosts API */
export const HOSTS_API = API_PREFIX + PLUGIN_NAME + '/hosts';

/** Data API */
export const DATA_API = API_PREFIX + PLUGIN_NAME + '/data';

/** Capture Profile API */
export const CAPTURE_PROFILE_API =
    API_PREFIX + PLUGIN_NAME + '/capture_profile';

/** Default Host */
export const DEFAULT_HOST = 'default';

/**
 * Based on palette of Kenneth Kelly's 22 colors of maximum contrast.
 * More information at page 5 of
 * https://eleanormaclure.files.wordpress.com/2011/03/colour-coding.pdf.
 * "F2F3F4" was removed because it's contrast against white is poor.
 */
export const KELLY_COLORS = [
  '0067A5', 'E68FAC', 'E25822', '008856', 'F99379', '604E97', 'F6A600',
  'B3446C', 'DCD300', '8DB600', '654522', '222222', '882D17', 'F3C300',
  '875692', 'F38400', 'A1CAF1', 'BE0032', 'C2B280', '848482', '2B3D26',
];

/**
 * Empty diagnostic content
 * diagnostics is input to the <diagnostic-view> component, used by graph viewer
 */
export const DIAGNOSTICS_DEFAULT = {
  info: [] as string[],
  warnings: [] as string[],
  errors: [] as string[],
};

/** The keys for form inputs for generating graph viewer */
export const GRAPH_CONFIG_KEYS =
    ['selectedModule', 'opName', 'graphWidth', 'showMetadata', 'mergeFusion'];

/** The tools generated by HLO proto. */
export const HLO_TOOLS =
    ['memory_viewer', 'graph_viewer'];

/** The query parameter keys used in trace viewer */
// TODO(yinzz): update the key in tf-trace-viewr.html to this one for
// consistency
export const TRACE_VIEWER_QUERY_PARAMS_KEYS = {
  'host': 'host',
};
